package com.huann305.notificationhelper.fullscreen

internal object FullScreenDataKeys {
    const val TITLE = "nhfs_title"
    const val MESSAGE = "nhfs_message"
    const val BIG_TEXT = "nhfs_big_text"
    const val TARGET_INTENT_URI = "nhfs_target_intent_uri"
    const val LAYOUT_RES_ID = "nhfs_layout_res_id"
    const val APP_ICON_RES_ID = "nhfs_app_icon_res_id"
    const val APP_ICON_URL = "nhfs_app_icon_url"
    const val IMAGE_RES_ID = "nhfs_image_res_id"
    const val IMAGE_URL = "nhfs_image_url"
    const val FULL_SCREEN_TITLE = "nhfs_full_screen_title"
    const val FULL_SCREEN_MESSAGE = "nhfs_full_screen_message"
    const val TIME_TEXT = "nhfs_time_text"
    const val DATE_TEXT = "nhfs_date_text"
    const val ACTION_TEXT = "nhfs_action_text"
    const val DISMISS_TEXT = "nhfs_dismiss_text"
    const val FALLBACK_TO_NORMAL_NOTIFICATION = "nhfs_fallback_to_normal_notification"
    const val LAUNCH_ACTIVITY_FALLBACK_ON_LOCK_SCREEN = "nhfs_launch_activity_fallback_on_lock_screen"
    const val CHANNEL_ID = "nhfs_channel_id"
    const val CHANNEL_NAME = "nhfs_channel_name"
    const val CHANNEL_DESCRIPTION = "nhfs_channel_description"
    const val CHANNEL_IMPORTANCE = "nhfs_channel_importance"
    const val NOTIFICATION_ID = "nhfs_notification_id"
    const val NOTIFICATION_TAG = "nhfs_notification_tag"
    const val REQUEST_CODE = "nhfs_request_code"
    const val SMALL_ICON_RES_ID = "nhfs_small_icon_res_id"
    const val COLOR = "nhfs_color"
    const val HAS_COLOR = "nhfs_has_color"
    const val PRIORITY = "nhfs_priority"
    const val CATEGORY = "nhfs_category"
    const val AUTO_CANCEL = "nhfs_auto_cancel"
    const val ONLY_ALERT_ONCE = "nhfs_only_alert_once"
}
