package com.huann305.notificationhelper

internal object NotificationDataKeys {
    const val TITLE = "nh_title"
    const val MESSAGE = "nh_message"
    const val BIG_TEXT = "nh_big_text"
    const val TARGET_INTENT_URI = "nh_target_intent_uri"
    const val BIG_LAYOUT_ENABLED = "nh_big_layout_enabled"
    const val BIG_COMPACT_LAYOUT_RES_ID = "nh_big_compact_layout_res_id"
    const val BIG_EXPANDED_LAYOUT_RES_ID = "nh_big_expanded_layout_res_id"
    const val BIG_ICON_RES_ID = "nh_big_icon_res_id"
    const val BIG_ICON_URL = "nh_big_icon_url"
    const val BIG_IMAGE_RES_ID = "nh_big_image_res_id"
    const val BIG_IMAGE_URL = "nh_big_image_url"
    const val BIG_ACTION_TEXT = "nh_big_action_text"
    const val BIG_LAYOUT_MODE = "nh_big_layout_mode"
    const val BIG_DECORATE_CUSTOM_VIEW = "nh_big_decorate_custom_view"
    const val CHANNEL_ID = "nh_channel_id"
    const val CHANNEL_NAME = "nh_channel_name"
    const val CHANNEL_DESCRIPTION = "nh_channel_description"
    const val CHANNEL_IMPORTANCE = "nh_channel_importance"
    const val NOTIFICATION_ID = "nh_notification_id"
    const val NOTIFICATION_TAG = "nh_notification_tag"
    const val REQUEST_CODE = "nh_request_code"
    const val SMALL_ICON_RES_ID = "nh_small_icon_res_id"
    const val COLOR = "nh_color"
    const val HAS_COLOR = "nh_has_color"
    const val PRIORITY = "nh_priority"
    const val CATEGORY = "nh_category"
    const val AUTO_CANCEL = "nh_auto_cancel"
    const val ONLY_ALERT_ONCE = "nh_only_alert_once"
}
